# Generated by Django 5.0.1 on 2024-01-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='Un-named', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(default='Un-named', max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rack_number', models.CharField(blank=True, max_length=255, null=True)),
                ('row_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_purchased', models.IntegerField()),
                ('vendor_details', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('sanction_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_id', models.IntegerField()),
                ('engineer_id', models.IntegerField()),
                ('technician_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('quantity_sanctioned', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.department')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
    ]
