# Generated by Django 5.0.1 on 2024-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='city',
        ),
        migrations.AlterField(
            model_name='material',
            name='rack_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='row_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
