# Generated by Django 5.0.1 on 2024-01-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_city_alter_material_rack_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
