# Generated by Django 4.1.13 on 2024-01-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
