# Generated by Django 4.1.13 on 2024-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_sanction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
