# Generated by Django 5.0.1 on 2024-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_purchase_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='Student', max_length=255),
        ),
    ]
