# Generated by Django 5.0.1 on 2024-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_category_material_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='material',
            name='critical_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
