# Generated by Django 5.0.1 on 2024-03-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_category_options_material_critical_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
