# Generated by Django 5.0.1 on 2024-03-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_rename_name_category_category_name'),
        ('materials', '0011_alter_sanction_log'),
    ]

    operations = [
    ]
