# Generated by Django 4.1.13 on 2024-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_merge_20240312_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
