# Generated by Django 5.0.1 on 2024-03-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_sanction_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_department', to='materials.department'),
        ),
    ]
