# Generated by Django 5.0.1 on 2024-03-13 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_department_sub_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sub_departments',
        ),
        migrations.AddField(
            model_name='department',
            name='parentDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='materials.department'),
        ),
    ]
