# Generated by Django 5.0.1 on 2024-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_remove_department_sub_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
