# Generated by Django 5.0.1 on 2024-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_purchase_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
