# Generated by Django 5.0.1 on 2024-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_alter_purchase_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=255)),
                ('technician_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sanction',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.department'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material'),
        ),
    ]
