# Generated by Django 5.0.1 on 2024-03-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_alter_purchase_material_alter_sanction_technician_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanction',
            old_name='technician_id',
            new_name='technician',
        ),
    ]
