# Generated by Django 5.0.1 on 2024-03-30 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_rename_technician_id_sanction_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='non_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
