# Generated by Django 5.0.1 on 2024-04-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_registerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.department'),
        ),
    ]
