# Generated by Django 4.1.13 on 2024-04-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_alter_registerrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
