# Generated by Django 4.1.13 on 2024-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_material_quantity_a_material_quantity_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='quantity_sanctioned',
        ),
        migrations.AddField(
            model_name='sanction',
            name='quantity_sanctioned_A',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='sanction',
            name='quantity_sanctioned_B',
            field=models.IntegerField(default=False),
        ),
    ]
