# Generated by Django 4.1.13 on 2024-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_remove_material_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='quantity_sanctioned_B',
        ),
        migrations.AddField(
            model_name='sanction',
            name='quantity_sanctioned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanction',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('A', 'B')], default='A', max_length=1),
        ),
    ]
