# Generated by Django 5.0.1 on 2024-04-08 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_purchase_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.department'),
        ),
    ]
