# Generated by Django 4.1.13 on 2024-04-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_remove_sanction_quantity_sanctioned_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='quantity_sanctioned',
        ),
    ]
