# Generated by Django 5.0.1 on 2024-04-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_technician_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanction',
            name='sanct_type',
            field=models.CharField(choices=[('A', 'A'), ('A', 'B')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='quantity_sanctioned',
            field=models.IntegerField(default=0),
        ),
    ]
