# Generated by Django 4.1.13 on 2024-04-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_remove_sanction_quantity_sanctioned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanction',
            old_name='quantity_sanctioned_A',
            new_name='quantity_sanctioned',
        ),
    ]
