# Generated by Django 4.1.13 on 2024-04-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_rename_quantity_sanctioned_a_sanction_quantity_sanctioned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanction',
            old_name='type',
            new_name='sanct_type',
        ),
    ]
