# Generated by Django 5.0.1 on 2024-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0030_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default='7879f2', max_length=6),
        ),
    ]
