# Generated by Django 4.1.13 on 2024-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=188307, max_length=6),
        ),
    ]
