# Generated by Django 5.0.1 on 2024-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=438872, max_length=6),
        ),
    ]
