# Generated by Django 5.0.1 on 2024-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=948310, max_length=6),
        ),
    ]
