# Generated by Django 4.1.13 on 2024-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=858417, max_length=6),
        ),
    ]
