# Generated by Django 4.2.7 on 2024-05-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0036_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parentDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_departments', to='materials.department'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=271056, max_length=6),
        ),
    ]
