# Generated by Django 4.2.7 on 2024-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0038_material_unit_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=648237, max_length=6),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
