# Generated by Django 4.2.7 on 2024-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0039_alter_emailverificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=164869, max_length=6),
        ),
    ]
