# Generated by Django 4.2.7 on 2024-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0040_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(default=750070, max_length=6),
        ),
    ]
